language: php
sudo: false

cache:
    directories:
      - $HOME/.composer/cache

php: 
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 5.4 #console output is different but works, TODO more flexible tests?

before_script:
  #coverage
  - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != "5.6" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then cp phpspec.yml.coverage phpspec.yml.dist; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require --no-update --dev henrikbjorn/phpspec-code-coverage; fi;'

  #composer
  - composer self-update
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.4" ]; then composer update --prefer-stable --prefer-lowest -o --prefer-dist; else composer update --prefer-stable -o --prefer-dist; fi;'
after_script:
  #coverage
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'

script: composer test
